### ISSUE TITLE
how can i install this plugin into my linux kodi?

### ISSUE THREAD

**Issue by lfarkas** [cancan101/xbmc-coursera#15]
at least a few lines of howto install would be useful.
thanks

**Comment by uvwild** [comment]
Bump :)

**Comment by cancan101** [comment]
I personally won't have time to write anything up, but PRs are welcome.

**Comment by karooga** [comment]
Any idea what version of kodi is works on?

**Comment by cancan101** [comment]
No.

**Comment by lfarkas** [comment]
it's working with the latest kodi release (except that it's repeatedly play the same video stream ie manually have to step to the next video lecture).

**Comment by emicol** [comment]
It seems to be very simple. Look at that : http://kodi.wiki/view/HOW-TO:Install_an_Add-on_from_a_zip_file

**Comment by jswhisperer** [comment]
@emicol would be super cool to just paste that link on the README.md for n00bs
Does seem like a lot of work though 😲
