### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by medyagh** [cancan101/xbmc-coursera#7]
hey I am not sure if this project is still active, but today I tried to install it thought a ZIP file and it yelled at me that dependency is not met, I went to my library addons and installed every single possible library addon (beautifulsou and others) and still got same error ...

should I give up or is there a way to make it work ?

Thanks

**Comment by cancan101** [comment]
There is a PR #6 right now that should fix this issue.

**Comment by medyagh** [comment]
are you gonna merge that PR ? or how I can download that PR separately?

**Comment by cancan101** [comment]
The PR will be merged soon.

**Comment by cancan101** [comment]
That PR has been merged.
